# Generated by Django 5.0.6 on 2025-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_tipo_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('passageiro', 'Passageiro'), ('ecotaxista', 'EcoTaxista')], max_length=20),
        ),
    ]
