# Generated by Django 5.0.6 on 2026-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0008_corrida_status_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacaoping',
            name='bearing',
            field=models.FloatField(blank=True, help_text='Direção da bússola em graus (0-360).', null=True),
        ),
    ]
